# Generated by Django 6.1 on 2026-10-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingRegistration',
        ),
    ]
