"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path
from dotenv import load_dotenv


# ==========================================
# BASE DIRECTORY
# ==========================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================================
# ENVIRONMENT VARIABLES
# ==========================================

load_dotenv()


# ==========================================
# TWILIO
# ==========================================

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_API_KEY = os.getenv("TWILIO_API_KEY")
TWILIO_API_SECRET = os.getenv("TWILIO_API_SECRET")
TWILIO_VERIFY_SERVICE_SID = os.getenv("TWILIO_VERIFY_SERVICE_SID")


# ==========================================
# SECURITY
# ==========================================

SECRET_KEY = 'django-insecure-&&vf1r_t*l2d4y89_l1q_^8#i__=84=2=@g&v%3#og)8pcd13v'

DEBUG = True

ALLOWED_HOSTS = []


# ==========================================
# APPLICATIONS
# ==========================================

INSTALLED_APPS = [

    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Project apps
    'accounts',
    'assessments',
    'doubts',
    'matching',
    'profiles',
    'reviews',
    'skills',
    'learning',
]


# ==========================================
# MIDDLEWARE
# ==========================================

MIDDLEWARE = [

    # CORS should be near the top
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',

    # Required for request.session
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==========================================
# CUSTOM USER
# ==========================================

AUTH_USER_MODEL = "accounts.User"


# ==========================================
# REST FRAMEWORK
# ==========================================

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

}


# ==========================================
# CORS
# ==========================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://vercel.com/agentx4/peerlearn",
]

CORS_ALLOW_CREDENTIALS = True


# ==========================================
# SESSION COOKIE
# ==========================================

# Required because registration data and OTP
# are stored in Django session.

SESSION_COOKIE_SAMESITE = "Lax"

SESSION_COOKIE_SECURE = False


# ==========================================
# CSRF COOKIE
# ==========================================

CSRF_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SECURE = False


# ==========================================
# URL CONFIGURATION
# ==========================================

ROOT_URLCONF = 'backend.urls'


# ==========================================
# TEMPLATES
# ==========================================

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]


# ==========================================
# WSGI
# ==========================================

WSGI_APPLICATION = 'backend.wsgi.application'


# ==========================================
# DATABASE
# ==========================================

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',

    }

}


# ==========================================
# PASSWORD VALIDATION
# ==========================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# ==========================================
# INTERNATIONALIZATION
# ==========================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AGORA_APP_ID = os.getenv("AGORA_APP_ID", "")
AGORA_APP_CERTIFICATE = os.getenv("AGORA_APP_CERTIFICATE", "")
# ==========================================
# STATIC FILES
# ==========================================

STATIC_URL = 'static/'


# ==========================================
# EMAIL
# ==========================================

MAILERS = {

    'default': {

        'BACKEND':
        'django.core.mail.backends.smtp.EmailBackend',

        'OPTIONS': {

            'host': 'smtp.gmail.com',

            'port': 587,

            'username':
            os.getenv('EMAIL_HOST_USER'),

            'password':
            os.getenv('EMAIL_HOST_PASSWORD'),

            'use_tls': True,

        },

    },

}


DEFAULT_FROM_EMAIL = os.getenv(
    'EMAIL_HOST_USER'
)